application: igctest23112013
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: todo.py 
